[tool.poetry]
name = "p-trace"
version = "0.1.0"
description = ""
authors = ["duanming"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
fastapi = {extras = ["all"], version = "^0.110.2"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
